name: seqpicker
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Core dependencies
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - biopython>=1.81
  - pyfastx>=1.0.0

  # External bioinformatics tools
  - cd-hit>=4.8.1
  - mafft>=7.508
  - hmmer>=3.3.2
  - seqkit>=2.3.0

  # Development tools
  - poetry>=1.4.0
  - pytest>=7.4.0
  - black>=23.7.0
  - isort>=5.12.0
  - mypy>=1.5.1
  - ruff>=0.0.291
  - ipykernel

  # Documentation
  - mkdocs>=1.4.0
  - mkdocs-material>=9.1.0
  - mkdocstrings>=0.22.0
  - mkdocstrings-python>=1.1.0

  # Additional useful tools
  - pre-commit>=3.3.0
  - conda-lock>=2.1.0

  - pip:
      - -e .